language: python
python:
    - "3.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=src/main.cpp
install:
    - pip install -U platformio
script:
    - pio test -e native
